In [2]:
import numpy as np

In [2]:
%%timeit
quadrati = []
for i in range(1000000):
    quadrati.append(i**2)

723 ms ± 12.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
quadrati

NameError: name 'quadrati' is not defined

In [ ]:
%%timeit
quadrati = np.arange(0, 1000000)**2


In [ ]:
quadrati

### Creare gli array unidimensionali

In [ ]:
array_di_zeri = np.zeros(10)
array_di_zeri

In [ ]:
array_di_zeri.dtype

In [ ]:
array_di_zeri_int = np.zeros(10, dtype=np.int8)
array_di_zeri_int

In [ ]:
array_di_uni = np.ones(10)
array_di_uni

In [ ]:
array_di_cinque = np.ones(10)*5  ##di chiama broadcast
array_di_cinque

In [ ]:
lista = [1, 2, 3, 4, 5, 1000]
array_da_lista_numeri = np.array(lista)
array_da_lista_numeri #array di numeri

In [ ]:
lista = [1, 2, 3, 4, 5, 1000, "c"]
array_da_lista_numeri = np.array(lista)
array_da_lista_numeri #array di stringhe

In [ ]:
np.random.uniform(3, 5) #float a caso

In [ ]:
float_casuali = np.random.uniform(3, 5, 10) #array di float casuali

In [ ]:
int_casuali = np.random.randint(1, 7, 10) #10 numeri interi tra 1(incluso) e 7(escluso)
int_casuali

In [ ]:
alice = np.random.randint(1, 7, 10)
bob = np.random.randint(1, 7, 10)

In [ ]:
print(f"lanci del dado di alice: {alice}")
print(f"lanci del dado di alice: {bob}")

In [ ]:
alice > bob

In [ ]:
print(f"alice batte bob {np.count_nonzero(alice > bob)} volte")

In [ ]:
vittorie_alice = alice > bob #alice > bob e un array di bool
vittorie_alice.dtype

In [ ]:
array_di_interi = np.arange(4, 10)
array_di_interi

In [ ]:
quadrati = np.arange(1, 11)**2
quadrati

In [ ]:
array1 = np.arange(1, 5)
array1

In [ ]:
array2 = np.ones(4)
array2

In [ ]:
array1.dtype

In [ ]:
array2.dtype

In [ ]:
somma = array1 + array2
somma

In [ ]:
somma.dtype

### Creazione array 1D

array di zeri:

    np. zeros()

array di uni:

    np.ones()

array da liste:

    np.array()
    
array d interi crescenti:

    np. arange

array pseudocasuali:

    np.random.randint
    np.random.uniform

### Array pseudocasuali

In [4]:
np. random.randint(1, 3, 10)

array([1, 1, 2, 2, 1, 1, 1, 2, 2, 1])

In [5]:
np.random.uniform(0, 1, 10)

array([0.92779233, 0.63279723, 0.11103343, 0.58837336, 0.74647099,
       0.08153843, 0.08501717, 0.55658757, 0.01287538, 0.60261686])

In [8]:
np.random.normal(175, 12, 10)  #sorteggia flot secondo dev. standard

array([178.62379479, 162.91770711, 185.8514077 , 187.73600131,
       185.32498656, 180.96046156, 169.46519696, 180.81925573,
       170.13424165, 160.73898955])

In [24]:
altezze = np.random.normal(175, 2, 10000)
altezze

array([177.17086804, 174.7539795 , 176.19485963, ..., 174.60392828,
       175.54352834, 174.81425087])

In [25]:
np.mean(altezze)

174.9935397034083

In [26]:
np.std(altezze)

1.9913118614622298

## Indicizzazione per booleani
#### Una delle funzioni più potenti di numpy

In [28]:
lanci_dadi = np.random.randint(1, 7, 10)
lanci_dadi

array([5, 4, 6, 1, 4, 3, 3, 3, 2, 6])

quali sono i lanci in cui il valore del dado era > 3?

In [30]:
lanci_gt_3 = lanci_dadi > 3
lanci_gt_3

array([ True,  True,  True, False,  True, False, False, False, False,
        True])

In [32]:
lanci_dadi[lanci_gt_3] # indicizzo array con array di booleani (filtra l'array dando solo valori > 3)

array([5, 4, 6, 4, 6])

In [33]:
nomi = np.array(["Alice", "Bob", "Trudy"])
voti = np.array([7, 9, 2])

quali alunni sono sufficienti?

In [35]:
nomi[voti >= 6]

array(['Alice', 'Bob'], dtype='<U5')

In [37]:
alice[alice > bob]

array([6, 5, 4, 5, 5, 4])

### Array bidimesionali
Es: 
- un' immagine in scale di grigi
- un' immagine a colori (RGB) è costituita da 3 array bidimensionale
- un' immagine a colori (RGBA - A = alpha per trasparenza) è costituita da 4 array bidimensionale
- i dati in forma di tabella


In [6]:
matrice_di_zeri = np.zeros((3, 6))
matrice_di_zeri

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
matrice_di_zeri.shape  #dice che "forma" ha l'array 2d

(3, 6)

In [8]:
array1d_di_zeri = np.zeros(7)
array1d_di_zeri

array([0., 0., 0., 0., 0., 0., 0.])

In [9]:
array1d_di_zeri.shape

(7,)

In [10]:
np.ones((10, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
np.array(([1, 2, 3], [4, 5, "ciao"]))

array([['1', '2', '3'],
       ['4', '5', 'ciao']], dtype='<U11')

In [18]:
np.random.randint(1, 7, (10, 2))

array([[3, 2],
       [6, 1],
       [3, 5],
       [4, 4],
       [5, 1],
       [4, 5],
       [3, 4],
       [6, 2],
       [1, 4],
       [1, 2]])

In [19]:
np.random.uniform(0, 1, (4, 4))

array([[0.0879167 , 0.23117917, 0.56520325, 0.72265259],
       [0.030436  , 0.9393501 , 0.91189738, 0.16141891],
       [0.03817629, 0.89650222, 0.21447646, 0.80653663],
       [0.05571532, 0.03991172, 0.99746069, 0.10884552]])

In [22]:
array_3d = np.random.uniform(0, 1, (3, 3, 2)) # so ottengono 3 matrici 3*2
array_3d

array([[[0.94192168, 0.23378749],
        [0.43730311, 0.82286056],
        [0.07260631, 0.02450405]],

       [[0.30782582, 0.11063745],
        [0.35086412, 0.84638081],
        [0.55935683, 0.89399435]],

       [[0.91358595, 0.54624915],
        [0.41014315, 0.00362801],
        [0.52886721, 0.18020014]]])

In [23]:
array_3d.shape

(3, 3, 2)

### Operazioni matematiche di aggregazione

- somma
- max e min
- dev. standard
- somma cumulata
- media

In [27]:
# somma
array = np.arange(1, 101)
np.sum(array)

5050

In [29]:
# massimo/minimo
array = np.random.uniform(0, 1, 10)
array

array([0.08987527, 0.52855879, 0.27205169, 0.64627612, 0.81918841,
       0.61667446, 0.90410166, 0.51658035, 0.17037322, 0.51718376])

In [30]:
np.max(array) #massimo

0.9041016632969788

In [31]:
np.std(array) #deviazione standard

0.2509457050365091

In [33]:
array_di_uni = np.ones(10)
array_di_uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.cumsum(array_di_uni) #somma cumulata

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
prezzo_apple = 178
variazioni = np.array([8, 3, -20, 6])

In [38]:
prezzo_apple + np.cumsum(variazioni)

array([186, 189, 169, 175])

### Cambiare forma agli array

In [41]:
array_1d = np.arange(1, 13)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
array_1d.reshape((3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
array_1d.reshape((6, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [44]:
array_1d.reshape((3, -1))  #con il -1 il pc calcola il numero di colonne da solo

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Esercizio
Dato n generare array 2d fatto in questo modo

    [[1, 2, 3,..., n],
    [[1, 2, 3,..., n],
    ...
    ...
    [1, 2, 3,..., n]
  
con n righe

In [53]:
n = 4
array1d = np.arange(1, n*n+1)
array2d = (array1d%n).reshape(n, -1)
array2d

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 0]], dtype=int32)

In [56]:
array2d = 1 + np.roll(array2d, 1)  #"spinge" in avanti (a dx) tutti gli elementi dell'array
array2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int32)

In [57]:
array2d.reshape(-1)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4], dtype=int32)

In [58]:
array2d.flatten()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4], dtype=int32)

### Slicing

In [60]:
array1d = np.arange(1, 11)
array1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
array1d[3]

4

In [63]:
array1d[3:8]

array([4, 5, 6, 7, 8])

In [64]:
array1d[-1] #ultimo elemento

10

In [65]:
array1d[-2]

9

In [66]:
array1d[1:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
array1d[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
array1d[3:8:2]

array([4, 6, 8])

In [73]:
np.random.seed(10)  #blocca il seme
array2d = np.random.uniform(0, 1, (3,3))
array2d

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [74]:
array2d[0, 0]

0.771320643266746

In [75]:
array2d[1, 2]

0.22479664553084766

In [76]:
array2d[1:]  # da la 2 e 3 riga della matrice

array([[0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [77]:
array2d[:, 1:]  #toglie la prima colonna [righe, colonne, gap]

array([[0.02075195, 0.63364823],
       [0.49850701, 0.22479665],
       [0.76053071, 0.16911084]])

In [78]:
array2d[1:, 1:]

array([[0.49850701, 0.22479665],
       [0.76053071, 0.16911084]])

In [81]:
array2d[1:, 1:] = 0  #assgna alle colonne tolte 0
array2d

array([[0.77132064, 0.        , 0.        ],
       [0.74880388, 0.        , 0.        ],
       [0.19806286, 0.        , 0.        ]])