#### es4 p107
Considera 1000 classi da 25 alunni ciascuna. Per ognuna di esse simula il giorno di nascita di ciascun alunno estraendo un numero a caso tra 1 e 365 inclusi (i giorni dell'anno non bisestile sono 365). Calcola in quante delle mille classi ci sono almeno due alunni nati lo stesso giorno.

In [7]:
import numpy as np

In [8]:
classi = 1000
alunni = 25
np.random.seed(10)

compleanni = np.random.randint(1, 366, (classi, alunni))
compleanni

array([[266, 126,  16, ..., 178, 180,  55],
       [ 78,  14, 244, ..., 217,  16,  19],
       [119,  72, 345, ..., 345, 144, 135],
       ...,
       [ 28,  63, 327, ..., 252, 113, 196],
       [ 91,  74, 170, ...,   3, 222, 122],
       [147, 207, 186, ..., 263, 222,  72]])

In [27]:
np.unique(compleanni, axis=1)

array([[  9,  16,  17, ..., 357, 357, 364],
       [159, 244,  32, ...,  75, 314,  94],
       [290, 345, 134, ..., 272,   5, 307],
       ...,
       [239, 327, 231, ..., 223, 123, 302],
       [290, 170, 250, ...,  26, 271, 122],
       [ 60, 186, 364, ..., 136, 317,  74]])

In [11]:
np.count_nonzero?

In [17]:
np.unique?

In [21]:
a = np.array(([1, 2, 4, 4], [1, 4, 6, 6]))
a

array([[1, 2, 4, 4],
       [1, 4, 6, 6]])

In [24]:
np.unique(a, return_counts=True, axis=0)

(array([[1, 2, 4, 4],
        [1, 4, 6, 6]]),
 array([1, 1], dtype=int64))

In [28]:
unici = np.unique(a, axis=1)
unici

array([[1, 2, 4],
       [1, 4, 6]])