#### es9 p107
Due giocatori si affrontano in una partita a dadi: ogni volta che un giocatore ottiene un numero maggiore del suo rivale guadagna un punto, mentre se entrambi i giocatori ottengono lo stesso numero guadagnano mezzo punto ciascuno.
> Simula una partita di 1000 lanci e registra i risultati di 10 partite.

> Se un giocatore utilizzasse un dado truccato in cui il 5 e il 6 avessero una probabilità doppia di uscire rispetto agli altri numeri, potremmo riuscire a capirlo?

In [2]:
import numpy as np

In [3]:
partite = 10
lanci = 1000

giocatore1 = np.random.randint(1, 7, (partite, lanci))
giocatore2 = np.random.randint(1, 7, (partite, lanci))

In [4]:
giocatore1

array([[6, 3, 6, ..., 4, 4, 2],
       [1, 6, 6, ..., 6, 5, 6],
       [6, 3, 6, ..., 3, 1, 4],
       ...,
       [3, 4, 2, ..., 2, 5, 6],
       [4, 6, 3, ..., 4, 6, 3],
       [2, 3, 3, ..., 6, 3, 4]])

In [5]:
giocatore2

array([[3, 4, 6, ..., 3, 4, 2],
       [2, 4, 1, ..., 4, 5, 1],
       [5, 4, 5, ..., 6, 4, 5],
       ...,
       [2, 4, 1, ..., 3, 3, 6],
       [1, 4, 6, ..., 5, 4, 1],
       [4, 2, 2, ..., 3, 5, 4]])

In [6]:
giocatore1[giocatore1 > giocatore2]

array([6, 3, 6, ..., 6, 4, 6])

In [7]:
giocatore2[giocatore1 < giocatore2]

array([4, 5, 5, ..., 6, 4, 5])